data:extend({
	{
		type = "int-setting",
		name = "ch-solar-max-production-mw",
		setting_type = "startup",
		default_value = 60,
		minimum_value = 1,
	},
	{
		type = "int-setting",
		name = "ch-solar-max-temp",
		setting_type = "startup",
		default_value = 600,
		minimum_value = 1,
	},
	{
		type = "int-setting",
		name = "ch-tower-capture-radius",
		setting_type = "startup",
		default_value = 35,
		minimum_value = 1,
	},
	{
		type = "double-setting",
		name = "ch-fluid-temp-per-mirror",
		setting_type = "startup",
		default_value = 1.1,
		minimum_value = 0.1,
	},
	{
		type = "double-setting",
		name = "ch-k2-production-mult",
		setting_type = "startup",
		default_value = 1.9,
		minimum_value = 0,
	},

	{
		type = "double-setting",
		name = "ch-laser-dmg-modifier",
		setting_type = "startup",
		default_value = 1.0,
		minimum_value = 0.1,
	},
	{
		type = "int-setting",
		name = "ch-laser-max-range",
		setting_type = "startup",
		default_value = 150,
		minimum_value = 1,
	},
	{
		type = "int-setting",
		name = "ch-laser-min-range",
		setting_type = "startup",
		default_value = 6,
		minimum_value = 1,
	},
	{
		type = "bool-setting",
		name = "ch-enable-beams",
		setting_type = "runtime-global",
		default_value = true,
	},
})
